### PR TITLE
Handle empty arrays in a forward nested mutation

### LINKED ISSUE #1: Nested mutation with updateById set to an empty array and a and create fails
Combining an `updateById` set to an empty array with a nested `create` causes the mutation to fail with an error similar to this: `GraphQLError: Cannot read properties of undefined (reading 'parentToParentId')`

Example query:

```graphql
mutation {
  updateParentById(
    input: {
      id: 1
      parentPatch: {
        childrenUsingId: {
          updateById: [],
          create: {
            id: 1,
            parentId: 1,
            name: "child"
          }
        }
      }
    }
  ) {
    parent {
      id
      name
      childrenByParentId {
        nodes {
          id
          parentId
          name
        }
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by andrisak**
Closes #1

### CODE REVIEW

File: src/PostgraphileNestedMutationsPlugin.js [hunk 1]
```diff
@@ -651,7 +651,11 @@ module.exports = function PostGraphileNestedMutationPlugin(builder) {
               );
             }
 
-            if (fieldValue.updateById || fieldValue.updateByNodeId) {
+            if (
+              // check for null and empty array
+              (fieldValue.updateById && fieldValue.updateById.length > 0) ||
+              fieldValue.updateByNodeId
```
Comment (johnciprian) [inline src/PostgraphileNestedMutationsPlugin.js]: Is it possible for `updateByNodeId` to be an array?

**Review by johnciprian — COMMENTED** [review]
I left a question for you.

File: src/PostgraphileNestedMutationsPlugin.js (hunk 1 above)
Comment (andrisak) [reply src/PostgraphileNestedMutationsPlugin.js]: Good point. The schema actually allows it, so I have added a test for it and adjusted this check.
